build/gcc: Fix Makefile to use c++17
or else build breaks like this:

  astyle.h:332:44: error: ‘std::string_view’ has not been declared
    332 |         const std::string* findHeader(std::string_view line, int i,
        |                                            ^~~~~~~~~~~